name: Setup
description: Setup the environment for the release
inputs:
  ref:
    description: The git ref to build on
    required: false
  fetch-depth:
    description: The depth of the git checkout
    required: false
  optionals:
    description: Optional arguments to pass to the setup
    required: false
    default: ""
  python-version:
    description: The python version to use
    required: false
    default: "3.12"
  app-id:
    description: The GitHub App ID
    required: true
  private-key:
    description: The GitHub token to use
    required: true
  repositories:
    description: The repositories to get tokens for.
    required: false
    default: duploctl
outputs:
  token:
    description: The GitHub App token
    value: ${{ steps.app-token.outputs.token }}
runs:
  using: "composite"
  steps:

  - name: Create GitHub App Token
    uses: actions/create-github-app-token@v1
    id: app-token
    with:
      app-id: ${{ inputs.app-id }}
      private-key: ${{ inputs.private-key }}
      repositories: ${{ inputs.repositories }}

  - name: Checkout Code
    uses: actions/checkout@v4
    with:
      ref: ${{ inputs.ref }}
      fetch-depth: ${{ inputs.fetch-depth }}
      token: ${{ steps.app-token.outputs.token }}
      # persist-credentials: false

  - name: Set up Python ${{ inputs.python-version }}
    uses: actions/setup-python@v5
    with:
      python-version: ${{ inputs.python-version }}
      cache: pip

  - name: Install Dependencies
    shell: bash
    env:
      OPTIONALS: ${{ inputs.optionals }}
    run: pip install .$OPTIONALS
