services:

  duploctl:
    image: duplocloud/duploctl:latest
    container_name: duploctl
    build:
      target: runner
      args:
        PY_VERSION: ${PY_VERSION:-3.12}
      tags:
      - duplocloud/duploctl:latest
      - duplocloud/duploctl:${GIT_SHA:-latest}
      - duplocloud/duploctl:${GIT_REF:-latest}
      - duplocloud/duploctl:${GIT_TAG:-latest}
      x-bake:
        platforms:
        - linux/amd64
        - linux/arm64
        cache-to: type=gha,scope=runner,mode=max
        cache-from: type=gha,scope=runner
    environment:
      DUPLO_HOST: ${DUPLO_HOST:-}
      DUPLO_TOKEN: ${DUPLO_TOKEN:-}
      DUPLO_TENANT: ${DUPLO_TENANT:-}
      DUPLO_OUTPUT: yaml

  duploctl-bin:
    image: duplocloud/duploctl:bin
    container_name: duploctl-bin
    build:
      target: bin
      args:
        PY_VERSION: ${PY_VERSION:-3.12}
      x-bake:
        platforms:
        - linux/amd64
        - linux/arm64
        output: type=local,dest=./dist
        cache-to: type=gha,scope=installer,mode=max
        cache-from: type=gha,scope=installer

