# generated by duploctl pipeline, do no edit
class Duploctl < Formula
  desc "Command-line tools for Duplocloud"
  homepage "https://github.com/duplocloud/duploctl"
  version "{version}"
  license "MIT"
  base_url = "#{{homepage}}/releases/download/v#{{version}}/duploctl-#{{version}}"

  on_macos do
    url "#{{base_url}}-darwin-amd64.tar.gz"
    sha256 "{macos_sha}"
  end

  on_linux do
    url "#{{base_url}}-linux-amd64.tar.gz"
    sha256 "{linux_sha}"
  end

  def install
    bin.install "duploctl"
  end

  test do
    system "duploctl --version"
  end
end
